### ISSUE TITLE
Preferred dump speed ignored

### ISSUE THREAD

**Issue by gingerbeardman** [SabreTools/DICUI#178] opened 2019-12-28 10:28 UTC
# Problem
1. I have preferred dump speed set to X
1. Each time I a disc is recognised it is set to 20

# Expected
Preferred dump speed is honoured.

# Actual
Dump speed is set to 20 on every disc insertion.

# Versions 
DICUI 1.15-204 (downloaded 2019-12-23 via AppVeyor)

**Comment by mnadareski** [comment] 2020-01-27 05:44
Closing as duplicate of https://github.com/SabreTools/DICUI/issues/177

**Closed by mnadareski** 2020-01-27 05:44 UTC
Labels: duplicate

**Comment by gingerbeardman** [comment] 2020-01-27 14:20
Apologies for missing the bug immediately before this one! Oops.
